name: thyna_core
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  another_stepper: ^1.2.2
  dio: ^5.6.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_dotenv: ^5.1.0
  flutter_inappwebview: ^6.1.15
  flutter_svg: ^2.0.10+1
  get:
    git:
      url: https://github.com/jonataslaw/getx
      ref: master
  google_fonts: ^6.2.1
  onesignal_flutter: ^5.2.5
  open_filex: ^4.5.0
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  supabase_flutter: ^2.6.0
  url_launcher: ^6.3.0

# dependency_overrides:
#   flutter_inappwebview_android:
#     git:
#       url: https://github.com/holzgeist/flutter_inappwebview
#       path: flutter_inappwebview_android
#       ref: d89b1d32638b49dfc58c4b7c84153be0c269d057

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/"
